### ISSUE TITLE
Save malfunction v3.0a

### ISSUE THREAD

**Issue by vvVoDkAvv** [viciious/d32xr#70]
Save feature completely non-functional on Mega Everdrive x3. Doesn't ever register reaching a checkpoint even after completing several levels.

Problem encounterted on this hardware:
Mega Everdrive x3, Lexar 2GB Micro SD card
Model 1 Sega Genesis, Signetics processor
Model 1 Sega CD
Launch Sega 32x

**Comment by viciious** [comment]
[Doom 32X Resurrection - v3.0bb.xdelta.zip](https://github.com/viciious/d32xr/files/12417612/Doom.32X.Resurrection.-.v3.0bb.xdelta.zip)

Please try this ROM patch + drop this file into MEGA/SAVE directory on your SD cart so that the game would be able to detect an old Everdrive model: https://github.com/viciious/d32xr/raw/master/extras/megasave/D32XR.32x

**Comment by viciious** [comment]
Fixed in v3.1
